# Generated by Django 4.2.9 on 2024-01-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Birds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("common_name", models.CharField(max_length=254)),
                ("scientific_name", models.CharField(max_length=254)),
                ("probable_age", models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="BirdsDetail",
            fields=[
                ("common_name", models.CharField(max_length=254)),
                (
                    "scientific_name",
                    models.CharField(max_length=254, primary_key=True, serialize=False),
                ),
                ("birds_description", models.TextField()),
                ("birds_image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="BirdsStatus",
            fields=[
                (
                    "status_code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("status_name", models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="NodeDevice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("node_id", models.CharField(max_length=254)),
                ("node_location", models.CharField(max_length=254)),
                ("node_date", models.CharField(max_length=254)),
                ("node_time", models.CharField(max_length=254)),
                ("node_image", models.ImageField(upload_to="")),
                (
                    "scientific_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlapi.birdsdetail",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="birdsdetail",
            name="status_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mlapi.birdsstatus"
            ),
        ),
    ]
